# Generated by Django 3.0.8 on 2020-07-22 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_transaction_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='labels',
            field=models.ManyToManyField(blank=True, to='core.Label'),
        ),
    ]
